// react-sample/src/chart/BasicKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function BasicKLineChart () {
  useEffect(() => {
    const kLineChart = init('basic-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('basic-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">基础展示</p>
      <div id="basic-k-line" className="k-line-chart"/>
    </div>
  )
}

// ng-sample/src/app/k-line-chart/basic/basic-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-basic-k-kline-chart',
  templateUrl: './basic-k-line-chart.component.html',
})
export class BasicKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('basic-k-line');
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('basic-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">基础展示</p>
  <div id="basic-k-line" class="k-line-chart"></div>
</div>
