// react-sample/src/App.tsx
import React from 'react'
import ChartType from './chart/ChartType'
import Indicator from './chart/Indicator'
import Theme from './chart/Theme'
import Language from './chart/Language'
import Tooltip from './chart/Tooltip'
import Timezone from './chart/Timezone'
import Overlay from './chart/Overlay'
import LoadMore from './chart/LoadMore'
import Update from './chart/Update'

import './app.css'

function App() {
  return (
    <div
      className="app">
      <ChartType/>
      <Indicator/>
      <Theme/>
      <Language/>
      <Tooltip/>
      <Timezone/>
      <Overlay/>
      <LoadMore/>
      <Update/>
    </div>
  )
}

export default App

// ng-sample/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: []
})
export class AppComponent {
  title = 'ng-sample';
}

<div class="app" role="main">
  <app-chart-type></app-chart-type>
  <app-indicator></app-indicator>
  <app-theme></app-theme>
  <app-language></app-language>
  <app-tooltip></app-tooltip>
  <app-y-axis></app-y-axis>
  <app-timezone></app-timezone>
  <app-overlay></app-overlay>
  <app-load-more></app-load-more>
  <app-update></app-update>
</div>
