// react-sample/src/Layout.tsx
import React from 'react'

export interface LayoutProps {
  title: string
  children: React.ReactNode
}

const Layout: React.FC<LayoutProps> = ({ title, children }) => {
  return (
    <div
      className="k-line-chart-container">
      <h3
        className="k-line-chart-title">{title}</h3>
      {children}
    </div>
  )
}


export default Layout

// ng-sample/src/app/components/layout.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html'
})
export class LayoutComponent {
  @Input() title: string;
}

<div
  class="k-line-chart-container">
  <h3
    class="k-line-chart-title">{{title}}</h3>
  <ng-content></ng-content>
</div>
