// react-sample/src/chart/LoadMore.tsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

export default function LoadMore () {
  useEffect(() => {
    const chart = init('load-more-k-line')
    chart?.applyNewData(generatedDataList(Date.now(), 5000, 200), true)
    chart?.loadMore(timestamp => {
      setTimeout(() => {
        const firstData = chart.getDataList()[0]
        chart.applyMoreData(generatedDataList(timestamp as number, firstData.close, 100), true)
      }, 2000)
    })
    return () => {
      dispose('load-more-k-line')
    }
  }, [])
  return (
    <Layout
      title="加载历史数据">
      <div id="load-more-k-line" className="k-line-chart"/>
    </Layout>
  )
}

// ng-sample/src/app/components/load-more.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, Nullable } from 'klinecharts';

import generatedDataList from '../generatedDataList';

@Component({
  selector: 'app-load-more',
  templateUrl: './load-more.component.html',
})
export class LoadMoreComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const chart: Nullable<Chart> = init('load-more-k-line');
    chart?.loadMore(timestamp => {
      setTimeout(() => {
        const firstData = chart.getDataList()[0];
        chart.applyMoreData(generatedDataList(timestamp as number, firstData.close, 100), true);
      }, 2000);
      return {};
    });
    chart?.applyNewData(generatedDataList(Date.now(), 5000, 200), true);
  }

  ngOnDestroy(): void {
    dispose('load-more-k-line');
  }
}
