// react-sample/src/chart/Theme.tsx
import React, { useEffect, useState, useRef } from 'react'
import { init, dispose, Chart } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

const themes = [
  { key: 'dark', text: '深色' },
  { key: 'light', text: '浅色' }
]

export default function CustomThemeKLineChart () {
  const chart = useRef<Chart | null>()
  const [theme, setTheme] = useState('light')

  useEffect(() => {
    chart.current = init('style-k-line')
    chart.current?.applyNewData(generatedDataList())
    return () => {
      dispose('style-k-line')
    }
  }, [])

  useEffect(() => {
    chart.current?.setStyles(theme)
  }, [theme])

  return (
    <Layout
      title="主题">
      <div
        id="style-k-line"
        style={theme === 'dark' ? { backgroundColor: '#1f2126' } : {}}
        className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        {
          themes.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => { setTheme(key) }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}

// ng-sample/src/app/components/theme.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, Nullable } from 'klinecharts';

import generatedDataList from '../generatedDataList';

@Component({
  selector: 'app-theme',
  templateUrl: './theme.component.html',
})
export class ThemeComponent implements AfterViewInit, OnDestroy {
  theme = 'light';
  private chart: Nullable<Chart> = null;
  ngAfterViewInit(): void {
    this.chart = init('theme-k-line');
    this.chart?.applyNewData(generatedDataList());
  }

  setTheme(theme: string) {
    this.theme = theme;
    this.chart?.setStyles(theme);
  }

  ngOnDestroy(): void {
    dispose('theme-k-line');
  }
}

<app-layout title="主题">
  <div id="theme-k-line" class="k-line-chart" [ngStyle]="{'backgroundColor': theme === 'dark' ? '#1f2126' : ''}"></div>
  <div
    class="k-line-chart-menu-container">
    <button
      (click)="setTheme('dark')">
      深色
    </button>
    <button
      (click)="setTheme('light')">
      浅色
    </button>
  </div>
</app-layout>
