// react-sample/src/chart/Timezone.tsx
import React, { useEffect, useRef } from 'react'
import { init, dispose, Chart } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

const timezones = [
  { key: 'Asia/Shanghai', text: '上海' },
  { key: 'Europe/Berlin', text: '柏林' },
  { key: 'America/Chicago', text: '芝加哥' }
]

export default function Timezone () {
  const chart = useRef<Chart | null>()
  useEffect(() => {
    chart.current = init('timezone-k-line')
    chart.current?.applyNewData(generatedDataList())
    return () => {
      dispose('timezone-k-line')
    }
  }, [])

  return (
    <Layout
      title="时区设置">
      <div
        id="timezone-k-line" className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        {
          timezones.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => {
                  chart.current && chart.current.setTimezone(key)
                }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}

// ng-sample/src/app/components/timezone.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, Nullable } from 'klinecharts';

import generatedDataList from '../generatedDataList';

@Component({
  selector: 'app-timezone',
  templateUrl: './timezone.component.html',
})
export class TimezoneComponent implements AfterViewInit, OnDestroy {
  private chart: Nullable<Chart> = null;

  timezones = [
    { key: 'Asia/Shanghai', text: '上海' },
    { key: 'Europe/Berlin', text: '柏林' },
    { key: 'America/Chicago', text: '芝加哥' }
  ];

  ngAfterViewInit(): void {
    this.chart = init('timezone-k-line');
    this.chart?.applyNewData(generatedDataList());
  }

  setTimezone(timezone: string) {
    this.chart?.setTimezone(timezone);
  }

  ngOnDestroy(): void {
    dispose('timezone-k-line');
  }
}
