// react-sample/src/chart/Update.tsx
import React, { useEffect } from 'react'
import { init, dispose, Chart } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

function updateData (chart: Chart | null) {
  setTimeout(() => {
    if (chart) {
      const dataList = chart.getDataList()
      const lastData = dataList[dataList.length - 1]
      const newData = generatedDataList(lastData.timestamp, lastData.close, 1)[0]
      newData.timestamp += 1000 * 60
      chart.updateData(newData)
    }
    updateData(chart)
  }, 1000)
}

export default function Update () {
  useEffect(() => {
    const chart = init('update-k-line')
    chart?.applyNewData(generatedDataList())
    updateData(chart)
    return () => {
      dispose('update-k-line')
    }
  }, [])
  return (
    <Layout
      title="实时更新">
      <div id="update-k-line" className="k-line-chart"/>
    </Layout>
  )
}

// ng-sample/src/app/components/update.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, KLineData, Nullable } from 'klinecharts';

import generatedDataList from '../generatedDataList';

@Component({
  selector: 'app-update',
  templateUrl: './update.component.html',
})
export class UpdateComponent implements AfterViewInit, OnDestroy {
  private chart: Nullable<Chart> = null;
  ngAfterViewInit(): void {
    this.chart = init('update-k-line');
    this.chart?.applyNewData(generatedDataList());
    this.updateData();
  }

  updateData() {
    setTimeout (() => {
      const dataList: KLineData[] = this.chart?.getDataList() ?? [];
      const lastData = dataList[dataList.length - 1];
      const newData = generatedDataList(lastData.timestamp, lastData.close, 1)[0];
      newData.timestamp += 60 * 1000;
      this.chart?.updateData(newData);
      this.updateData();
    }, 1000);
  }

  ngOnDestroy(): void {
    dispose('update-k-line');
  }
}

<app-layout title="实时更新">
  <div id="update-k-line" class="k-line-chart"></div>
</app-layout>
