// react-sample/src/chart/YAxis.tsx
import React, { useEffect, useState, useRef } from 'react'
import { init, dispose, Chart, YAxisType } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

const types = [
  { key: 'normal', text: '线性轴' },
  { key: 'percentage', text: '百分比轴' },
  { key: 'log', text: '对数轴' }
]

export default function CustomThemeKLineChart () {
  const chart = useRef<Chart | null>()
  const [type, setType] = useState('normal')

  useEffect(() => {
    chart.current = init('y-axis-k-line')
    chart.current?.applyNewData(generatedDataList())
    return () => {
      dispose('y-axis-k-line')
    }
  }, [])

  useEffect(() => {
    chart.current?.setStyles({
      yAxis: { type: type as YAxisType }
    })
  }, [type])

  return (
    <Layout
      title="Y轴">
      <div
        id="y-axis-k-line"
        className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        {
          types.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => { setType(key) }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}

// ng-sample/src/app/components/y-axis.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, Nullable, YAxisType } from 'klinecharts';

import generatedDataList from '../generatedDataList';

@Component({
  selector: 'app-y-axis',
  templateUrl: './y-axis.component.html',
})
export class YAxisComponent implements AfterViewInit, OnDestroy {
  private chart: Nullable<Chart> = null;
  ngAfterViewInit(): void {
    this.chart = init('y-axis-k-line');
    this.chart?.applyNewData(generatedDataList());
  }

  setType(type: string) {
    this.chart?.setStyles({
      yAxis: { type: type as YAxisType },
    });
  }

  ngOnDestroy(): void {
    dispose('y-axis-k-line');
  }
}

<app-layout title="Y轴">
  <div id="y-axis-k-line" class="k-line-chart"></div>
  <div
    class="k-line-chart-menu-container">
    <button
      (click)="setType('normal')">
      线性轴
    </button>
    <button
      (click)="setType('percentage')">
      百分比轴
    </button>
    <button
      (click)="setType('log')">
      对数轴
    </button>
  </div>
</app-layout>
