// vue-sample/src/components/YAxisTextInsideKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">Y轴文字在图表内部</p>
    <div id="y-axis-text-inside-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'YAxisTextInsideKLineChart',
    mounted: function () {
      const kLineChart = init('y-axis-text-inside-k-line')
      kLineChart.setStyleOptions({
        yAxis: {
          tickText: {
            position: 'inside'
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('y-axis-text-inside-k-line')
    }
  }
</script>

// ng-sample/src/app/k-line-chart/y-axis-text-inside/y-axis-text-inside-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-y-axis-text-inside-k-line-chart',
  templateUrl: './y-axis-text-inside-k-line-chart.component.html',
})
export class YAxisTextInsideKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('y-axis-text-inside-k-line');
    kLineChart.setStyleOptions({
      yAxis: {
        tickText: {
          position: 'inside'
        }
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('y-axis-text-inside-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">Y轴文字在图表内部</p>
  <div id="y-axis-text-inside-k-line" class="k-line-chart"></div>
</div>
