// react-sample/src/chart/RealTimeKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function RealTimeKLineChart () {
  useEffect(() => {
    const kLineChart = init('real-time-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    kLineChart.setCandleStickChartType('real_time')
    return () => {
      dispose('real-time-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">分时图</p>
      <div id="real-time-k-line" className="k-line-chart"/>
    </div>
  )
}

// ng-sample/src/app/k-line-chart/real-time/real-time-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-real-time-k-kline-chart',
  templateUrl: './real-time-k-line-chart.component.html',
})
export class RealTimeKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('real-time-k-line');
    kLineChart.setCandleStickChartType('real_time');
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('real-time-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">分时图</p>
  <div id="real-time-k-line" class="k-line-chart"></div>
</div>
