// react-sample/src/chart/CustomTechnicalIndicatorKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import { priceAndVolumeTrend } from 'klinecharts-technical-indicator'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function CustomTechnicalIndicatorKLineChart () {
  let kLineChart
  useEffect(() => {
    kLineChart = init('custom-technical-indicator-k-line')
    kLineChart.addCustomTechnicalIndicator(priceAndVolumeTrend)
    kLineChart.createTechnicalIndicator('PVT', 50)
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('custom-technical-indicator-k-line')
    }
  })
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">自定义技术指标</p>
      <div id="custom-technical-indicator-k-line" className="k-line-chart"/>
    </div>
  )
}

// ng-sample/src/app/k-line-chart/custom-technical-indicator/custom-technical-indicator-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose } from 'klinecharts';
import { priceAndVolumeTrend } from 'klinecharts-technical-indicator';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-custom-technical-indicator-k-kline-chart',
  templateUrl: './custom-technical-indicator-k-line-chart.component.html',
})
export class CustomTechnicalIndicatorKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart = init('custom-technical-indicator-k-line');
    kLineChart.addCustomTechnicalIndicator(priceAndVolumeTrend);
    kLineChart.createTechnicalIndicator('PVT', 50);
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('custom-technical-indicator-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">自定义技术指标</p>
  <div id="custom-technical-indicator-k-line" class="k-line-chart"></div>
</div>
