// react-sample/src/chart/Theme.tsx
import React, { useEffect, useState, useRef } from 'react'
import { init, dispose, Chart } from 'klinecharts'
import generatedDataList from '../generatedDataList'
import Layout from '../Layout'

const themes = [
  { key: 'dark', text: '深色' },
  { key: 'light', text: '浅色' }
]

export default function CustomThemeKLineChart () {
  const chart = useRef<Chart | null>()
  const [theme, setTheme] = useState('light')

  useEffect(() => {
    chart.current = init('style-k-line')
    chart.current?.applyNewData(generatedDataList())
    return () => {
      dispose('style-k-line')
    }
  }, [])

  useEffect(() => {
    chart.current?.setStyles(theme)
  }, [theme])

  return (
    <Layout
      title="主题">
      <div
        id="style-k-line"
        style={theme === 'dark' ? { backgroundColor: '#1f2126' } : {}}
        className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        {
          themes.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => { setTheme(key) }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}

// vue-sample/src/chart/Theme.vue
<template>
  <Layout title="主题">
    <div
      id="custom-theme-k-line"
      class="k-line-chart"
      v-bind:style="{ backgroundColor: theme === 'dark' ? '#1f2126' : '' }"
    />
    <div class="k-line-chart-menu-container">
      <button v-on:click="setTheme('dark')">深色</button>
      <button v-on:click="setTheme('light')">浅色</button>
    </div>
  </Layout>
</template>

<script>
import { dispose, init } from "klinecharts";
import generatedDataList from "../generatedDataList";
import Layout from "../Layout.vue";

export default {
  name: "ChartTheme",
  components: { Layout },
  data: function () {
    return {
      theme: "light",
    };
  },
  mounted: function () {
    this.chart = init("custom-theme-k-line");
    this.chart.applyNewData(generatedDataList());
  },
  methods: {
    setTheme: function (theme) {
      this.theme = theme;
      this.chart.setStyles(theme);
    },
  },
  unmounted: function () {
    dispose("custom-theme-k-line");
  },
};
</script>
