// vue-sample/src/components/CandleStickTechnicalIndicatorKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">蜡烛图技术指标设置</p>
    <div
      id="candle-stick-technical-indicator-type-k-line"
      class="k-line-chart"/>
    <div class="k-line-chart-setting-container">
      <button
        v-on:click="setTechnicalIndicatorType('NO')"
        class="k-line-chart-setting-button"
        v-bind:class="{'k-line-chart-setting-button-selected': technicalIndicatorType === 'NO'}">
        NO
      </button>
      <button
        v-on:click="setTechnicalIndicatorType('MA')"
        class="k-line-chart-setting-button"
        v-bind:class="{'k-line-chart-setting-button-selected': technicalIndicatorType === 'MA'}">
        MA
      </button>
      <button
        v-on:click="setTechnicalIndicatorType('EMA')"
        class="k-line-chart-setting-button"
        v-bind:class="{'k-line-chart-setting-button-selected': technicalIndicatorType === 'EMA'}">
        EMA
      </button>
      <button
        v-on:click="setTechnicalIndicatorType('BOLL')"
        class="k-line-chart-setting-button"
        v-bind:class="{'k-line-chart-setting-button-selected': technicalIndicatorType === 'BOLL'}">
        BOLL
      </button>
      <button
        v-on:click="setTechnicalIndicatorType('SAR')"
        class="k-line-chart-setting-button"
        v-bind:class="{'k-line-chart-setting-button-selected': technicalIndicatorType === 'SAR'}">
        SAR
      </button>
    </div>
  </div>
</template>

<script>
  import {dispose, init} from "klinecharts"
  import generatedKLineDataList from "../generatedKLineDataList"

  export default {
    name: 'CandleStickTechnicalIndicatorKLineChart',
    data: function () {
      return {
        technicalIndicatorType: 'MA'
      }
    },
    mounted: function () {
      this.kLineChart = init('candle-stick-technical-indicator-type-k-line')
      this.kLineChart.applyNewData(generatedKLineDataList())
    },
    methods: {
      setTechnicalIndicatorType: function (technicalIndicatorType) {
        this.technicalIndicatorType = technicalIndicatorType
        this.kLineChart.setCandleStickTechnicalIndicatorType(technicalIndicatorType)
      }
    },
    destroyed: function () {
      dispose('candle-stick-technical-indicator-type-k-line')
    }
  }
</script>

// react-sample/src/chart/CandleStickTechnicalIndicatorKLineChart.jsx
import React, { useEffect, useState } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function CandleStickTechnicalIndicatorKLineChart () {
  let kLineChart
  const [technicalIndicatorType, setTechnicalIndicatorType] = useState('MA')

  useEffect(() => {
    kLineChart = init('candle-stick-technical-indicator-k-line')
  })

  useEffect(() => {
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('candle-stick-technical-indicator-k-line')
    }
  }, [])

  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">蜡烛图技术指标设置</p>
      <div id="candle-stick-technical-indicator-k-line" className="k-line-chart"/>
      <div className="k-line-chart-setting-container">
        <button
          className={`k-line-chart-setting-button ${technicalIndicatorType === 'NO' && 'k-line-chart-setting-button-selected'}`}
          onClick={() => {
            kLineChart.setCandleStickTechnicalIndicatorType('NO')
            setTechnicalIndicatorType('NO')
          }}>
          NO
        </button>
        <button
          className={`k-line-chart-setting-button ${technicalIndicatorType === 'MA' && 'k-line-chart-setting-button-selected'}`}
          onClick={() => {
            kLineChart.setCandleStickTechnicalIndicatorType('MA')
            setTechnicalIndicatorType('MA')
          }}>
          MA
        </button>
        <button
          className={`k-line-chart-setting-button ${technicalIndicatorType === 'EMA' && 'k-line-chart-setting-button-selected'}`}
          onClick={() => {
            kLineChart.setCandleStickTechnicalIndicatorType('EMA')
            setTechnicalIndicatorType('EMA')
          }}>
          EMA
        </button>
        <button
          className={`k-line-chart-setting-button ${technicalIndicatorType === 'BOLL' && 'k-line-chart-setting-button-selected'}`}
          onClick={() => {
            kLineChart.setCandleStickTechnicalIndicatorType('BOLL')
            setTechnicalIndicatorType('BOLL')
          }}>
          BOLL
        </button>
        <button
          className={`k-line-chart-setting-button ${technicalIndicatorType === 'SAR' && 'k-line-chart-setting-button-selected'}`}
          onClick={() => {
            kLineChart.setCandleStickTechnicalIndicatorType('SAR')
            setTechnicalIndicatorType('SAR')
          }}>
          SAR
        </button>
      </div>
    </div>
  )
}
