// ng-sample/src/app/k-line-chart/custom-technical-indicator-mark-k-line-chart/custom-technical-indicator-mark-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-custom-technical-indicator-mark-k-kline-chart',
  templateUrl: './custom-technical-indicator-mark-k-line-chart.component.html',
})
export class CustomTechnicalIndicatorMarkKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('custom-technical-indicator-mark-k-line');
    kLineChart.createPane('technicalIndicator', { height: 150 });
    kLineChart.subscribeDrawAction('drawTechnicalIndicator', (data) => {
      const { ctx, coordinate, technicalIndicatorData } = data;
      if (technicalIndicatorData.macd > 5) {
        ctx.font = '12px';
        const text = `${technicalIndicatorData.macd.toFixed(4)}`;
        ctx.textBaseline = 'middle';
        ctx.fillStyle = '#fff';
        ctx.fillText(text, coordinate.x, coordinate.macd + 6);
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('custom-technical-indicator-mark-k-line');
  }
}

<app-layout title="自定义指标标记">
  <div id="custom-technical-indicator-mark-k-line" class="k-line-chart"></div>
</app-layout>

// react-sample/src/chart/CustomTechnicalIndicatorMarkKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'
import Layout from '../Layout'

export default function CustomTechnicalIndicatorMarkKLineChart () {
  useEffect(() => {
    const kLineChart = init('custom-technical-indicator-mark-k-line')
    kLineChart.createPane('technicalIndicator', { height: 150 })
    kLineChart.applyNewData(generatedKLineDataList())
    kLineChart.subscribeDrawAction('drawTechnicalIndicator', (data) => {
      const { ctx, coordinate, technicalIndicatorData } = data
      if (technicalIndicatorData.macd > 5) {
        ctx.font = '12px'
        const text = `${technicalIndicatorData.macd.toFixed(4)}`
        ctx.textBaseline = 'middle'
        ctx.fillStyle = '#fff'
        ctx.fillText(text, coordinate.x, coordinate.macd + 6)
      }
    })
    return () => {
      dispose('custom-technical-indicator-mark-k-line')
    }
  }, [])
  return (
    <Layout
      title="自定义指标标记">
      <div id="custom-technical-indicator-mark-k-line" className="k-line-chart"/>
    </Layout>
  )
}
