// ng-sample/src/app/k-line-chart/load-more/load-more-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-load-more-k-kline-chart',
  templateUrl: './load-more-k-line-chart.component.html',
})
export class LoadMoreKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('load-more-k-line');
    kLineChart.loadMore(timestamp => {
      setTimeout(() => {
        const firstData = kLineChart.getDataList()[0];
        kLineChart.applyMoreData(generatedKLineDataList(timestamp, firstData.close, 100), true);
      }, 2000);
      return {};
    });
    kLineChart.applyNewData(generatedKLineDataList(Date.now(), 5000, 200), true);
  }

  ngOnDestroy(): void {
    dispose('load-more-k-line');
  }
}

<app-layout title="加载更多">
  <div id="load-more-k-line" class="k-line-chart"></div>
</app-layout>

// react-sample/src/chart/LoadMoreKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'
import Layout from '../Layout'

export default function LoadMoreKLineChart () {
  useEffect(() => {
    const kLineChart = init('load-more-k-line')
    kLineChart.applyNewData(generatedKLineDataList(Date.now(), 5000, 200), true)
    kLineChart.loadMore(timestamp => {
      setTimeout(() => {
        const firstData = kLineChart.getDataList()[0]
        kLineChart.applyMoreData(generatedKLineDataList(timestamp, firstData.close, 100), true)
      }, 2000)
    })
    return () => {
      dispose('load-more-k-line')
    }
  }, [])
  return (
    <Layout
      title="加载历史数据">
      <div id="load-more-k-line" className="k-line-chart"/>
    </Layout>
  )
}
