// ng-sample/src/app/k-line-chart/percentage-y-axis/percentage-y-axis-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-percentage-y-axis-k-line-chart',
  templateUrl: './percentage-y-axis-k-line-chart.component.html',
})
export class PercentageYAxisKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('percentage-y-axis-k-line');
    kLineChart.setStyleOptions({
      yAxis: {
        type: 'percentage'
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('percentage-y-axis-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">百分比Y轴</p>
  <div id="percentage-y-axis-k-line" class="k-line-chart"></div>
</div>

// react-sample/src/chart/PercentageYAxisKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function PercentageYAxisKLineChart () {
  useEffect(() => {
    const kLineChart = init('percentage-y-axis-k-line')
    kLineChart.setStyleOptions({
      yAxis: {
        type: 'percentage'
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('percentage-y-axis-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">百分比Y轴</p>
      <div id="percentage-y-axis-k-line" className="k-line-chart"/>
    </div>
  )
}
