// vue-sample/src/components/RealTimeKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">分时图</p>
    <div id="real-time-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../generatedKLineDataList'

export default {
  name: 'RealTimeKLineChart',
  mounted: function () {
    const kLineChart = init('real-time-k-line')
    kLineChart.setCandleStickChartType('real_time')
    kLineChart.applyNewData(generatedKLineDataList())
  },
  destroyed: function () {
    dispose('real-time-k-line')
  }
}
</script>

// react-sample/src/chart/RealTimeKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function RealTimeKLineChart () {
  useEffect(() => {
    const kLineChart = init('real-time-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    kLineChart.setCandleStickChartType('real_time')
    return () => {
      dispose('real-time-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">分时图</p>
      <div id="real-time-k-line" className="k-line-chart"/>
    </div>
  )
}
