// ng-sample/src/app/k-line-chart/timezone/timezone-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-timezone-k-kline-chart',
  templateUrl: './timezone-k-line-chart.component.html',
})
export class TimezoneKLineChartComponent implements AfterViewInit, OnDestroy {
  private kLineChart: Chart;

  timezones = [
    { key: 'Asia/Shanghai', text: '上海' },
    { key: 'Europe/Berlin', text: '柏林' },
    { key: 'America/Chicago', text: '芝加哥' }
  ];

  ngAfterViewInit(): void {
    this.kLineChart = init('timezone-k-line');
    this.kLineChart.applyNewData(generatedKLineDataList());
  }

  setTimezone(timezone: string) {
    this.kLineChart.setTimezone(timezone);
  }

  ngOnDestroy(): void {
    dispose('timezone-k-line');
  }
}

<app-layout title="时区设置">
  <div id="timezone-k-line" class="k-line-chart"></div>
  <div class="k-line-chart-menu-container">
    <button
      *ngFor="let timezone of timezones"
      (click)="setTimezone(timezone.key)">
      {{timezone.text}}
    </button>
  </div>
</app-layout>

// react-sample/src/chart/TimezoneKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'
import Layout from '../Layout'

const timezones = [
  { key: 'Asia/Shanghai', text: '上海' },
  { key: 'Europe/Berlin', text: '柏林' },
  { key: 'America/Chicago', text: '芝加哥' }
]

export default function TimezoneKLineChart () {
  let kLineChart
  useEffect(() => {
    kLineChart = init('timezone-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('timezone-k-line')
    }
  }, [])

  return (
    <Layout
      title="时区设置">
      <div
        id="timezone-k-line" className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        {
          timezones.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => {
                  kLineChart.setTimezone(key)
                }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}
