// vue-sample/src/components/UpdateKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">仿真实时</p>
    <div id="update-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'UpdateKLineChart',
    mounted: function () {
      const kLineChart = init('update-k-line')
      const updateData = () => {
        setTimeout(() => {
          const dataList = kLineChart.getDataList()
          const lastData = dataList[dataList.length - 1]
          const newData = generatedKLineDataList(lastData.timestamp, lastData.close, 1)[0]
          kLineChart.updateData(newData)
          updateData(kLineChart)
        }, 1000)

      }
      kLineChart.applyNewData(generatedKLineDataList())
      updateData()
    },
    methods: {

    },
    destroyed: function () {
      dispose('update-k-line')
    }
  }
</script>

// react-sample/src/chart/UpdateKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function UpdateKLineChart () {
  function updateData (kLineChart) {
    setTimeout(() => {
      if (kLineChart) {
        const dataList = kLineChart.getDataList()
        const lastData = dataList[dataList.length - 1]
        const newData = generatedKLineDataList(lastData.timestamp, lastData.close, 1)[0]
        kLineChart.updateData(newData)
      }
      updateData(kLineChart)
    }, 1000)
  }

  useEffect(() => {
    const kLineChart = init('update-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    updateData(kLineChart)
    return () => {
      dispose('update-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">仿真实时</p>
      <div id="update-k-line" className="k-line-chart"/>
    </div>
  )
}
