// ng-sample/src/app/k-line-chart/update/update-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import {init, dispose, Chart, KLineData} from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-update-k-kline-chart',
  templateUrl: './update-k-line-chart.component.html',
})
export class UpdateKLineChartComponent implements AfterViewInit, OnDestroy {
  private kLineChart: Chart;
  ngAfterViewInit(): void {
    this.kLineChart = init('update-k-line');
    this.kLineChart.applyNewData(generatedKLineDataList());
    this.updateData();
  }

  updateData() {
    setTimeout (() => {
      const dataList: KLineData[] = this.kLineChart.getDataList();
      const lastData = dataList[dataList.length - 1];
      const newData = generatedKLineDataList(lastData.timestamp, lastData.close, 1)[0];
      this.kLineChart.updateData(newData);
      this.updateData();
    }, 1000);
  }

  ngOnDestroy(): void {
    dispose('update-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">仿真实时</p>
  <div id="update-k-line" class="k-line-chart"></div>
</div>

// react-sample/src/chart/UpdateKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function UpdateKLineChart () {
  function updateData (kLineChart) {
    setTimeout(() => {
      if (kLineChart) {
        const dataList = kLineChart.getDataList()
        const lastData = dataList[dataList.length - 1]
        const newData = generatedKLineDataList(lastData.timestamp, lastData.close, 1)[0]
        kLineChart.updateData(newData)
      }
      updateData(kLineChart)
    }, 1000)
  }

  useEffect(() => {
    const kLineChart = init('update-k-line')
    kLineChart.applyNewData(generatedKLineDataList())
    updateData(kLineChart)
    return () => {
      dispose('update-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">仿真实时</p>
      <div id="update-k-line" className="k-line-chart"/>
    </div>
  )
}
