// vue-sample/src/components/WithoutYAxisKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">隐藏Y轴</p>
    <div id="without-y-axis-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'WithoutYAxisKLineChart',
    mounted: function () {
      const kLineChart = init('without-y-axis-k-line')
      kLineChart.setStyleOptions({
        yAxis: {
          display: false
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('without-y-axis-k-line')
    }
  }
</script>

// react-sample/src/chart/WithoutYAxisKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function WithoutYAxisKLineChart () {
  useEffect(() => {
    const kLineChart = init('without-y-axis-k-line')
    kLineChart.setStyleOptions({
      yAxis: {
        display: false
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('without-y-axis-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">不显示Y轴</p>
      <div id="without-y-axis-k-line" className="k-line-chart"/>
    </div>
  )
}
