// react-sample/src/chart/LeftYAxisKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function LeftYAxisKLineChart () {
  useEffect(() => {
    const kLineChart = init('left-y-axis-k-line')
    kLineChart.setStyleOptions({
      yAxis: {
        position: 'left'
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('left-y-axis-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">Y轴在左边</p>
      <div id="left-y-axis-k-line" className="k-line-chart"/>
    </div>
  )
}

// ng-sample/src/app/k-line-chart/left-y-axis/left-y-axis-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-left-y-axis-k-kline-chart',
  templateUrl: './left-y-axis-k-line-chart.component.html',
})
export class LeftYAxisKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('left-y-axis-k-line');
    kLineChart.setStyleOptions({
      yAxis: {
        position: 'left'
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('left-y-axis-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">Y轴在左边</p>
  <div id="left-y-axis-k-line" class="k-line-chart"></div>
</div>
