// react-sample/src/chart/CustomCandleStickLabelKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function CustomCandleStickLabelKLineChart () {
  let kLineChart
  useEffect(() => {
    kLineChart = init('custom-candlestick-label-k-line')
    kLineChart.setStyleOptions({
      floatLayer: {
        prompt: {
          candleStick: {
            labels: ['开', '收', '涨幅'],
            values: kLineData => {
              return [
                {
                  value: kLineData.open.toFixed(2)
                }, {
                  value: kLineData.close.toFixed(2)
                }, {
                  value: `${((kLineData.close - kLineData.open) / kLineData.open * 100).toFixed(2)}%`,
                  color: kLineData.close - kLineData.open > 0 ? '#26A69A' : '#EF5350'
                }
              ]
            }
          }
        }
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('custom-candlestick-label-k-line')
    }
  })
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">自定义蜡烛图数据提示</p>
      <div id="custom-candlestick-label-k-line" className="k-line-chart"/>
    </div>
  )
}

// vue-sample/src/components/CustomCandleStickLabelKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">自定义蜡烛图label</p>
    <div id="custom-candle-stick-label-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'CustomCandleStickLabelKLineChart',
    mounted: function () {
      const kLineChart = init('custom-candle-stick-label-k-line')
      kLineChart.setStyleOptions({
        floatLayer: {
          prompt: {
            candleStick: {
              labels: ['开', '收', '涨幅'],
              values: kLineData => {
                return [
                  {
                    value: kLineData.open.toFixed(2)
                  }, {
                    value: kLineData.close.toFixed(2)
                  }, {
                    value: `${((kLineData.close - kLineData.open) / kLineData.open * 100).toFixed(2)}%`,
                    color: kLineData.close - kLineData.open > 0 ? '#26A69A' : '#EF5350'
                  }
                ]
              }
            }
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('custom-candle-stick-label-k-line')
    }
  }
</script>
