// react-sample/src/chart/FloatPromptKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function FloatPromptKLineChart () {
  useEffect(() => {
    const kLineChart = init('float-prompt-k-line')
    kLineChart.setStyleOptions({
      floatLayer: {
        prompt: {
          candleStick: {
            showType: 'rect'
          }
        }
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('float-prompt-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">浮动提示框</p>
      <div id="float-prompt-k-line" className="k-line-chart"/>
    </div>
  )
}

// vue-sample/src/components/FloatPromptKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">浮动框提示</p>
    <div id="float-prompt-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'FloatPromptKLineChart',
    mounted: function () {
      const kLineChart = init('float-prompt-k-line')
      kLineChart.setStyleOptions({
        floatLayer: {
          prompt: {
            candleStick: {
              showType: 'rect'
            }
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('float-prompt-k-line')
    }
  }
</script>
