// ng-sample/src/app/k-line-chart/language/language-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-language-k-kline-chart',
  templateUrl: './language-k-line-chart.component.html',
})
export class LanguageKLineChartComponent implements AfterViewInit, OnDestroy {
  language = 'zh-CN';
  private kLineChart: Chart;
  ngAfterViewInit(): void {
    this.kLineChart = init('language-k-line');
    this.kLineChart.applyNewData(generatedKLineDataList());
  }

  setLanguage(language: string) {
    this.language = language;
    this.kLineChart.setStyleOptions({
      candle: {
        tooltip: {
          labels: language === 'zh-CN'
            ? ['时间：', '开：', '收：', '高：', '低：', '成交量：']
            : language === 'zh-HK'
              ? ['時間：', '開：', '收：', '高：', '低：', '成交量：']
              : ['T: ', 'O: ', 'C: ', 'H: ', 'L: ', 'V: ']
        }
      }
    });
  }

  ngOnDestroy(): void {
    dispose('language-k-line');
  }
}

<app-layout title="多语言">
  <div id="language-k-line" class="k-line-chart"></div>
  <div class="k-line-chart-menu-container">
    <button
      class="k-line-chart-setting-button"
      (click)="setLanguage('zh-CN')">
      简体中文
    </button>
    <button
      class="k-line-chart-setting-button"
      (click)="setLanguage('zh-HK')">
      繁體中文
    </button>
    <button
      class="k-line-chart-setting-button"
      (click)="setLanguage('en-US')">
      English
    </button>
  </div>
</app-layout>

// vue-sample/src/components/LanguageKLineChart.vue
<template>
  <Layout title="多语言">
    <div
      id="language-k-line"
      class="k-line-chart"/>
    <div class="k-line-chart-menu-container">
      <button
        v-on:click="setLanguage('zh-CN')">
        简体中文
      </button>
      <button
        v-on:click="setLanguage('zh-HK')">
        繁體中文
      </button>
      <button
        v-on:click="setLanguage('en-US')">
        English
      </button>
    </div>
  </Layout>
</template>

<script>
  import {dispose, init} from "klinecharts"
  import generatedKLineDataList from "../generatedKLineDataList"
  import Layout from "@/Layout"

  function getLanguageOptions (language) {
    return {
      candle: {
        tooltip: {
          labels: language === 'zh-CN'
            ? ['时间：', '开：', '收：', '高：', '低：', '成交量：']
            : language === 'zh-HK'
              ? ['時間：', '開：', '收：', '高：', '低：', '成交量：']
              : ['T: ', 'O: ', 'C: ', 'H: ', 'L: ', 'V: ']
        }
      }
    }
  }

  export default {
    name: 'LanguageKLineChart',
    components: {Layout},
    mounted: function () {
      this.kLineChart = init('language-k-line')
      this.kLineChart.applyNewData(generatedKLineDataList())
    },
    methods: {
      setLanguage: function (language) {
        this.kLineChart.setStyleOptions(getLanguageOptions(language))
      }
    },
    destroyed: function () {
      dispose('language-k-line')
    }
  }
</script>
