// react-sample/src/chart/LoadMoreKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function LoadMoreKLineChart () {
  useEffect(() => {
    const kLineChart = init('load-more-k-line')
    kLineChart.applyNewData(generatedKLineDataList(null, null, 200), true)
    kLineChart.loadMore(timestamp => {
      setTimeout(() => {
        const firstData = kLineChart.getDataList()[0]
        kLineChart.applyMoreData(generatedKLineDataList(timestamp, firstData.close, 100), true)
      }, 2000)
    })
    return () => {
      dispose('load-more-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">加载历史数据</p>
      <div id="load-more-k-line" className="k-line-chart"/>
    </div>
  )
}

// vue-sample/src/components/LoadMoreKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">加载更多</p>
    <div id="load-more-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'LoadMoreKLineChart',
    mounted: function () {
      const kLineChart = init('load-more-k-line')
      kLineChart.loadMore(timestamp => {
        setTimeout(() => {
          const firstData = kLineChart.getDataList()[0]
          kLineChart.applyMoreData(generatedKLineDataList(timestamp, firstData.close, 100), true)
        }, 2000)
      })
      kLineChart.applyNewData(generatedKLineDataList(null, null , 200), true)
    },
    destroyed: function () {
      dispose('load-more-k-line')
    }
  }
</script>
