// react-sample/src/chart/TechnicalIndicatorLastDataPromptKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function TechnicalIndicatorLastDataPromptKLineChart () {
  useEffect(() => {
    const kLineChart = init('technical-indicator-last-data-prompt-k-line')
    kLineChart.setStyleOptions({
      technicalIndicator: {
        lastValueMark: {
          display: true
        }
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('technical-indicator-last-data-prompt-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">技术指标最后值提示</p>
      <div id="technical-indicator-last-data-prompt-k-line" className="k-line-chart"/>
    </div>
  )
}

// vue-sample/src/components/TechnicalIndicatorLastDataPromptKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">技术指标最后值标记</p>
    <div id="technical-indicator-last-data-prompt-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'TechnicalIndicatorLastDataPromptKLineChart',
    mounted: function () {
      const kLineChart = init('technical-indicator-last-data-prompt-k-line')
      kLineChart.setStyleOptions({
        technicalIndicator: {
          lastValueMark: {
            display: true
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('technical-indicator-last-data-prompt-k-line')
    }
  }
</script>
