// ng-sample/src/app/k-line-chart/technical-indicator/technical-indicator-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart, TechnicalIndicatorInfo } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

const fruits = [
  '🍏', '🍎', '🍐', '🍊', '🍋', '🍌',
  '🍉', '🍇', '🍓', '🍈', '🍒', '🍑',
  '🍍', '🥥', '🥝', '🥭', '🥑', '🍏'
];

// 自定义指标
const emojiTechnicalIndicator: TechnicalIndicatorInfo = {
  name: 'EMOJI',
  plots: [
    { key: 'emoji' }
  ],
  calcTechnicalIndicator: (kLineDataList) => {
    const result = [];
    kLineDataList.forEach(kLineData => {
      result.push({ emoji: kLineData.close, text: fruits[Math.floor(Math.random() * 17)] });
    });
    return result;
  },
  render: (
    ctx,
    { from, to, technicalIndicatorDataList },
    { barSpace },
    options, xAxis, yAxis
  ) => {
    ctx.font = `${barSpace}px Helvetica Neue`;
    ctx.textAlign = 'center';
    for (let i = from; i < to; i++) {
      const data = technicalIndicatorDataList[i];
      const x = xAxis.convertToPixel(i);
      const y = yAxis.convertToPixel(data.emoji);
      ctx.fillText(data.text, x, y);
    }
  }
};

@Component({
  selector: 'app-technical-indicator-k-line-chart',
  templateUrl: './technical-indicator-k-line-chart.component.html',
})
export class TechnicalIndicatorKLineChartComponent implements AfterViewInit, OnDestroy {
  mainTechnicalIndicatorTypes = ['MA', 'EMA', 'SAR'];
  subTechnicalIndicatorTypes = ['VOL', 'MACD', 'KDJ'];

  private kLineChart: Chart;

  private paneTag: string;

  ngAfterViewInit(): void {
    this.kLineChart = init('technical-indicator-k-line');
    this.kLineChart.addCustomTechnicalIndicator(emojiTechnicalIndicator);
    this.paneTag = this.kLineChart.createPane('technicalIndicator', { technicalIndicatorType: 'VOL', height: 100 });
    this.kLineChart.applyNewData(generatedKLineDataList());
  }

  setCandleTechnicalIndicator(type) {
    this.kLineChart.setTechnicalIndicatorType(type);
  }

  setSubTechnicalIndicator(type) {
    this.kLineChart.setTechnicalIndicatorType(type, false, this.paneTag);
  }

  ngOnDestroy(): void {
    dispose('technical-indicator-k-line');
  }
}

<app-layout title="技术指标">
  <div id="technical-indicator-k-line" class="k-line-chart"></div>
  <div
    class="k-line-chart-menu-container">
    <span style="padding-right: 10px">主图指标</span>
    <button
      *ngFor="let type of mainTechnicalIndicatorTypes"
      (click)="setCandleTechnicalIndicator(type)">
      {{type}}
    </button>
    <button
      (click)="setCandleTechnicalIndicator('EMOJI')">
      自定义
    </button>
    <span style="padding-right: 10px;padding-left: 12px">副图指标</span>
    <button
      *ngFor="let type of subTechnicalIndicatorTypes"
      (click)="setSubTechnicalIndicator(type)">
      {{type}}
    </button>
    <button
      (click)="setSubTechnicalIndicator('EMOJI')">
      自定义
    </button>
  </div>
</app-layout>

// vue-sample/src/components/TechnicalIndicatorKLineChart.vue
<template>
  <Layout title="技术指标">
    <div id="technical-indicator-k-line" class="k-line-chart"/>
    <div
      class="k-line-chart-menu-container">
      <span style="padding-right: 10px">主图指标</span>
      <button
        v-for="type in mainTechnicalIndicatorTypes"
        :key="type"
        v-on:click="setCandleTechnicalIndicator(type)">
        {{type}}
      </button>
      <button
        v-on:click="setCandleTechnicalIndicator('EMOJI')">
        自定义
      </button>
      <span style="padding-right: 10px;padding-left: 12px">副图指标</span>
      <button
        v-for="type in subTechnicalIndicatorTypes"
        :key="type"
        v-on:click="setSubTechnicalIndicator(type)">
        {{type}}
      </button>
      <button
        v-on:click="setSubTechnicalIndicator('EMOJI')">
        自定义
      </button>
    </div>
  </Layout>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'
  import Layout from "@/Layout"

  const fruits = [
    '🍏', '🍎', '🍐', '🍊', '🍋', '🍌',
    '🍉', '🍇', '🍓', '🍈', '🍒', '🍑',
    '🍍', '🥥', '🥝', '🥭', '🥑', '🍏'
  ]

  // 自定义指标
  const emojiTechnicalIndicator = {
    name: 'EMOJI',
    plots: [
      { key: 'emoji' }
    ],
    calcTechnicalIndicator: (kLineDataList) => {
      const result = []
      kLineDataList.forEach(kLineData => {
        result.push({ emoji: kLineData.close, text: fruits[Math.floor(Math.random() * 17)] })
      })
      return result
    },
    render: (
      ctx,
      { from, to, technicalIndicatorDataList },
      { barSpace },
      options, xAxis, yAxis
    ) => {
      ctx.font = `${barSpace}px Helvetica Neue`
      ctx.textAlign = 'center'
      for (let i = from; i < to; i++) {
        const data = technicalIndicatorDataList[i]
        const x = xAxis.convertToPixel(i)
        const y = yAxis.convertToPixel(data.emoji)
        ctx.fillText(data.text, x, y)
      }
    }
  }

  export default {
    name: 'TechnicalIndicatorKLineChart',
    components: {Layout},
    data: function () {
      return {
        mainTechnicalIndicatorTypes: ['MA', 'EMA', 'SAR'],
        subTechnicalIndicatorTypes: ['VOL', 'MACD', 'KDJ']
      }
    },
    mounted: function () {
      this.kLineChart = init('technical-indicator-k-line')
      this.kLineChart.addCustomTechnicalIndicator(emojiTechnicalIndicator)
      this.paneTag = this.kLineChart.createPane('technicalIndicator', { technicalIndicatorType: 'VOL', height: 100 })
      this.kLineChart.applyNewData(generatedKLineDataList())
    },
    methods: {
      setCandleTechnicalIndicator: function (type) {
        this.kLineChart.setTechnicalIndicatorType(type)
      },
      setSubTechnicalIndicator: function (type) {
        this.kLineChart.setTechnicalIndicatorType(type, false, this.paneTag)
      },
    },
    destroyed: function () {
      dispose('technical-indicator-k-line')
    }
  }
</script>
