// react-sample/src/chart/TooltipKLineChart.jsx
import React, { useRef, useState, useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'
import Layout from '../Layout'

function getTooltipOptions (candleShowType, candleShowRule, technicalIndicatorShowRule) {
  return {
    candle: {
      tooltip: {
        showType: candleShowType,
        showRule: candleShowRule,
        labels: ['开盘价：', '收盘价：', '涨跌幅：'],
        values: kLineData => {
          const change = (kLineData.close - kLineData.open) / kLineData.open * 100
          return [
            { value: kLineData.open.toFixed(2) },
            { value: kLineData.close.toFixed(2) },
            {
              value: `${change.toFixed(2)}%`,
              color: change < 0 ? '#EF5350' : '#26A69A'
            }
          ]
        }
      }
    },
    technicalIndicator: {
      tooltip: {
        showRule: technicalIndicatorShowRule
      }
    }
  }
}

const rules = [
  { key: 'always', text: '总是显示' },
  { key: 'follow_cross', text: '跟随十字光标' },
  { key: 'none', text: '不显示' }
]

export default function TooltipKLineChart () {
  const chart = useRef()
  const [candleShowType, setCandleShowType] = useState('standard')
  const [candleShowRule, setCandleShowRule] = useState('always')
  const [technicalIndicatorShowRule, setTechnicalIndicatorShowRule] = useState('always')

  useEffect(() => {
    chart.current = init('tooltip-k-line')
    chart.current.createTechnicalIndicator('MA', false, { id: 'candle_pane' })
    chart.current.createTechnicalIndicator('KDJ', false, { height: 80 })
    chart.current.applyNewData(generatedKLineDataList())
    return () => { dispose('tooltip-k-line') }
  }, [])

  useEffect(() => {
    chart.current && chart.current.setStyleOptions(getTooltipOptions(
      candleShowType, candleShowRule, technicalIndicatorShowRule
    ))
  }, [candleShowType, candleShowRule, technicalIndicatorShowRule])

  return (
    <Layout
      title="十字光标文字提示">
      <div id="tooltip-k-line" className="k-line-chart"/>
      <div
        className="k-line-chart-menu-container">
        <span style={{ paddingRight: 10 }}>主图显示类型</span>
        <button
          onClick={_ => { setCandleShowType('standard') }}>
          默认
        </button>
        <button
          onClick={_ => { setCandleShowType('rect') }}>
          矩形框
        </button>
      </div>
      <div
        className="k-line-chart-menu-container">
        <span style={{ paddingRight: 10 }}>k线提示显示规则</span>
        {
          rules.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => { setCandleShowRule(key) }}>
                {text}
              </button>
            )
          })
        }
      </div>
      <div
        className="k-line-chart-menu-container">
        <span style={{ paddingRight: 10 }}>指标提示显示规则</span>
        {
          rules.map(({ key, text }) => {
            return (
              <button
                key={key}
                onClick={_ => { setTechnicalIndicatorShowRule(key) }}>
                {text}
              </button>
            )
          })
        }
      </div>
    </Layout>
  )
}

// vue-sample/src/components/TooltipKLineChart.vue
<template>
  <Layout title="十字光标文字提示">
    <div id="tooltip-k-line" class="k-line-chart"/>
    <div
      class="k-line-chart-menu-container">
      <span style="padding-right: 10px">主图显示类型</span>
      <button
        v-on:click="setCandleShowType('standard')">
      默认
      </button>
      <button
        v-on:click="setCandleShowType('rect')">
      矩形框
      </button>
    </div>
    <div
      class="k-line-chart-menu-container">
      <span style="padding-right: 10px">k线提示显示规则</span>
      <button
        v-for="({ key, text }) in rules"
        :key="key"
        v-on:click="setCandleShowRule(key)">
        {{text}}
      </button>
    </div>
    <div
      class="k-line-chart-menu-container">
      <span style="padding-right: 10px">指标提示显示规则</span>
      <button
        v-for="({ key, text }) in rules"
        :key="key"
        v-on:click="setTechnicalIndicatorShowRule(key)">
        {{text}}
      </button>
    </div>
  </Layout>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'
  import Layout from "@/Layout"

  function getTooltipOptions (candleShowType, candleShowRule, technicalIndicatorShowRule) {
    return {
      candle: {
        tooltip: {
          showType: candleShowType,
          showRule: candleShowRule,
          labels: ['开盘价：', '收盘价：', '涨跌幅：'],
          values: kLineData => {
            const change = (kLineData.close - kLineData.open) / kLineData.open * 100
            return [
              { value: kLineData.open.toFixed(2) },
              { value: kLineData.close.toFixed(2) },
              {
                value: `${change.toFixed(2)}%`,
                color: change < 0 ? '#EF5350' : '#26A69A'
              }
            ]
          }
        }
      },
      technicalIndicator: {
        tooltip: {
          showRule: technicalIndicatorShowRule
        }
      }
    }
  }

  export default {
    name: 'TooltipKLineChart',
    components: {Layout},
    data: function () {
      return {
        rules: [
          { key: 'always', text: '总是显示' },
          { key: 'follow_cross', text: '跟随十字光标' },
          { key: 'none', text: '不显示' }
        ],
        candleShowType: 'standard',
        candleShowRule: 'always',
        technicalIndicatorShowRule: 'always'
      }
    },
    mounted: function () {
      this.kLineChart = init('tooltip-k-line')
      this.kLineChart.createTechnicalIndicator('MA', false, { id: 'candle_pane' })
      this.kLineChart.createTechnicalIndicator('KDJ', false, { height: 80 })
      this.kLineChart.applyNewData(generatedKLineDataList())
    },
    methods: {
      setCandleShowType: function (type) {
        this.candleShowType = type
        this.kLineChart.setStyleOptions(getTooltipOptions(
          type, this.candleShowRule, this.technicalIndicatorShowRule
        ))
      },
      setCandleShowRule: function (rule) {
        this.candleShowRule = rule
        this.kLineChart.setStyleOptions(getTooltipOptions(
          this.candleShowType, rule, this.technicalIndicatorShowRule
        ))
      },
      setTechnicalIndicatorShowRule: function (rule) {
        this.technicalIndicatorShowRule = rule
        this.kLineChart.setStyleOptions(getTooltipOptions(
          this.candleShowType, this.candleShowRule, rule
        ))
      },
    },
    destroyed: function () {
      dispose('tooltip-k-line')
    }
  }
</script>
