// ng-sample/src/app/k-line-chart/without-y-axis/without-y-axis-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-without-y-axis-k-kline-chart',
  templateUrl: './without-y-axis-k-line-chart.component.html',
})
export class WithoutYAxisKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('without-y-axis-k-line');
    kLineChart.setStyleOptions({
      yAxis: {
        display: false
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('without-y-axis-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">隐藏Y轴</p>
  <div id="without-y-axis-k-line" class="k-line-chart"></div>
</div>

// vue-sample/src/components/WithoutYAxisKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">隐藏Y轴</p>
    <div id="without-y-axis-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'WithoutYAxisKLineChart',
    mounted: function () {
      const kLineChart = init('without-y-axis-k-line')
      kLineChart.setStyleOptions({
        yAxis: {
          display: false
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('without-y-axis-k-line')
    }
  }
</script>
