// react-sample/src/chart/TechnicalIndicatorLastDataPromptKLineChart.jsx
import React, { useEffect } from 'react'
import { init, dispose } from 'klinecharts'
import generatedKLineDataList from '../utils/generatedKLineDataList'

export default function TechnicalIndicatorLastDataPromptKLineChart () {
  useEffect(() => {
    const kLineChart = init('technical-indicator-last-data-prompt-k-line')
    kLineChart.setStyleOptions({
      technicalIndicator: {
        lastValueMark: {
          display: true
        }
      }
    })
    kLineChart.applyNewData(generatedKLineDataList())
    return () => {
      dispose('technical-indicator-last-data-prompt-k-line')
    }
  }, [])
  return (
    <div className="k-line-chart-container">
      <p className="k-line-chart-title">技术指标最后值提示</p>
      <div id="technical-indicator-last-data-prompt-k-line" className="k-line-chart"/>
    </div>
  )
}

// ng-sample/src/app/k-line-chart/technical-indicator-last-data-prompt/technical-indicator-last-data-prompt-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-technical-indicator-last-data-prompt-k-line-chart',
  templateUrl: './technical-indicator-last-data-prompt-k-line-chart.component.html',
})
export class TechnicalIndicatorLastDataPromptKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('technical-indicator-last-data-prompt-k-line');
    kLineChart.setStyleOptions({
      technicalIndicator: {
        lastValueMark: {
          display: true
        }
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('technical-indicator-last-data-prompt-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">技术指标最后值提示</p>
  <div id="technical-indicator-last-data-prompt-k-line" class="k-line-chart"></div>
</div>
