// vue-sample/src/components/FollowCrosshairPromptKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">提示跟随十字光标</p>
    <div id="follow-crosshair-prompt-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'FollowCrosshairPromptKLineChart',
    mounted: function () {
      const kLineChart = init('follow-crosshair-prompt-k-line')
      kLineChart.setStyleOptions({
        floatLayer: {
          prompt: {
            displayRule: 'follow_cross'
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('follow-crosshair-prompt-k-line')
    }
  }
</script>

// ng-sample/src/app/k-line-chart/follow-crosshair-prompt/follow-crosshair-prompt-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-follow-crosshair-prompt-k-kline-chart',
  templateUrl: './follow-crosshair-prompt-k-line-chart.component.html',
})
export class FollowCrosshairPromptKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('follow-crosshair-prompt-k-line');
    kLineChart.setStyleOptions({
      floatLayer: {
        prompt: {
          displayRule: 'follow_cross'
        }
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('follow-crosshair-prompt-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">提示跟随十字光标</p>
  <div id="follow-crosshair-prompt-k-line" class="k-line-chart"></div>
</div>
