// vue-sample/src/components/FloatPromptKLineChart.vue
<template>
  <div class="k-line-chart-container">
    <p class="k-line-chart-title">浮动框提示</p>
    <div id="float-prompt-k-line" class="k-line-chart"/>
  </div>
</template>

<script>
  import {dispose, init} from 'klinecharts'
  import generatedKLineDataList from '../generatedKLineDataList'

  export default {
    name: 'FloatPromptKLineChart',
    mounted: function () {
      const kLineChart = init('float-prompt-k-line')
      kLineChart.setStyleOptions({
        floatLayer: {
          prompt: {
            candleStick: {
              showType: 'rect'
            }
          }
        }
      })
      kLineChart.applyNewData(generatedKLineDataList())
    },
    destroyed: function () {
      dispose('float-prompt-k-line')
    }
  }
</script>

// ng-sample/src/app/k-line-chart/float-prompt/float-prompt-k-line-chart.component.ts
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { init, dispose, Chart } from 'klinecharts';

import generatedKLineDataList from '../../generatedKLineDataList';

@Component({
  selector: 'app-float-prompt-k-kline-chart',
  templateUrl: './float-prompt-k-line-chart.component.html',
})
export class FloatPromptKLineChartComponent implements AfterViewInit, OnDestroy {
  ngAfterViewInit(): void {
    const kLineChart: Chart = init('float-prompt-k-line');
    kLineChart.setStyleOptions({
      floatLayer: {
        prompt: {
          candleStick: {
            showType: 'rect'
          }
        }
      }
    });
    kLineChart.applyNewData(generatedKLineDataList());
  }

  ngOnDestroy(): void {
    dispose('float-prompt-k-line');
  }
}

<div class="k-line-chart-container">
  <p class="k-line-chart-title">浮动框提示</p>
  <div id="float-prompt-k-line" class="k-line-chart"></div>
</div>
